#!/usr/bin/env bash

readonly MODEL_URL='https://storage.googleapis.com/unifyid-ml-vcm/models/tencent-ml-images/checkpoints/model.ckpt.tar.gz'
readonly MODEL_DIR='/home/jovyan/checkpoints'

mkdir -p "${MODEL_DIR}"
curl -LSs "${MODEL_URL}" | tar -C "${MODEL_DIR}" -xvzf-

# vi: ft=sh
