#!/usr/bin/env bash

set -exo pipefail

readonly MODEL_URL='https://storage.googleapis.com/unifyid-ml-vcm/models/tencent-ml-images/checkpoints/model.ckpt.tar.gz'
readonly MODEL_DIR='/home/jovyan/checkpoints'

mkdir -p "${MODEL_DIR}"
curl -LSs "${MODEL_URL}" | tar -C "${MODEL_DIR}" -xvzf-


jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib

jupyter contrib nbextension install --user
jupyter nbextension install --py --symlink ipympl
jupyter nbextension enable --py ipympl
jupyter nbextension enable --py widgetsnbextension

jupyter lab build

# vi: ft=sh
